#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openct
Version  : 0.6.20
Release  : 1
URL      : https://github.com/OpenSC/openct/archive/refs/tags/openct-0.6.20.tar.gz
Source0  : https://github.com/OpenSC/openct/archive/refs/tags/openct-0.6.20.tar.gz
Summary  : libopenct
Group    : Development/Tools
License  : LGPL-2.1
Requires: openct-bin = %{version}-%{release}
Requires: openct-lib = %{version}-%{release}
Requires: openct-man = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : doxygen
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxslt-bin
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(libpcsclite)
BuildRequires : pkgconfig(libusb)
BuildRequires : sed
Patch1: 0001-Stateless.patch

%description
Creating an installable package for Solaris Sunray (SRSS 3.1)
=============================================================

%package bin
Summary: bin components for the openct package.
Group: Binaries

%description bin
bin components for the openct package.


%package dev
Summary: dev components for the openct package.
Group: Development
Requires: openct-lib = %{version}-%{release}
Requires: openct-bin = %{version}-%{release}
Provides: openct-devel = %{version}-%{release}
Requires: openct = %{version}-%{release}

%description dev
dev components for the openct package.


%package doc
Summary: doc components for the openct package.
Group: Documentation
Requires: openct-man = %{version}-%{release}

%description doc
doc components for the openct package.


%package lib
Summary: lib components for the openct package.
Group: Libraries

%description lib
lib components for the openct package.


%package man
Summary: man components for the openct package.
Group: Default

%description man
man components for the openct package.


%prep
%setup -q -n openct-openct-0.6.20
cd %{_builddir}/openct-openct-0.6.20
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1671132120
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1671132120
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/openct/openct.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/ifdhandler
/usr/bin/ifdproxy
/usr/bin/openct-control
/usr/bin/openct-tool

%files dev
%defattr(-,root,root,-)
/usr/include/openct/apdu.h
/usr/include/openct/buffer.h
/usr/include/openct/conf.h
/usr/include/openct/ctapi.h
/usr/include/openct/device.h
/usr/include/openct/driver.h
/usr/include/openct/error.h
/usr/include/openct/ifd.h
/usr/include/openct/logging.h
/usr/include/openct/openct.h
/usr/include/openct/path.h
/usr/include/openct/protocol.h
/usr/include/openct/server.h
/usr/include/openct/socket.h
/usr/include/openct/tlv.h
/usr/include/openct/types.h
/usr/lib64/libopenct.so
/usr/lib64/libopenctapi.so
/usr/lib64/pkgconfig/libopenct.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/openct/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopenct.so.1
/usr/lib64/libopenct.so.1.0.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/openct-tool.1
